name: Restart GitHub Codespaces

on:
  schedule:
    # Run every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch: # Allows for manual triggering
    inputs:
      reason:
        description: 'Reason for restart'
        required: true

jobs:
  restart_codespace:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install the latest GitHub CLI
      - name: Install Latest GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt-get update
          sudo apt-get install gh -y

      # Step 3: Authenticate GitHub CLI using the Personal Access Token (PAT)
      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.CODESPACE_PAT }}" | gh auth login --with-token

      # Step 4: Get the active Codespace name
      - name: Get Codespace Name
        id: codespace_info
        run: |
          CODESPACE_NAME=$(gh codespace list --json name -q '.[0].name')
          echo "::set-output name=codespace_name::$CODESPACE_NAME"

      # Step 5: Stop the active Codespace
      - name: Stop Codespace
        run: |
          gh codespace stop -c "${{ steps.codespace_info.outputs.codespace_name }}"

      # Step 6: Start a new Codespace
      - name: Start new Codespace
        run: |
          REPO_URL="https://github.com/Cxncer/NOX-Telegram-Bot"
          gh codespace create --repo "$REPO_URL"
